vich_uploader:
    db_driver: orm

    mappings:
        project_screen_mobile:
           uri_prefix: /img/project/screen_mobile
           upload_destination: '%kernel.project_dir%/%app.public_dir%/img/project/screen_mobile'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        project_screen_desktop:
           uri_prefix: /img/project/screen_desktop
           upload_destination: '%kernel.project_dir%/%app.public_dir%/img/project/screen_desktop'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        skill_logo:
           uri_prefix: /img/skill
           upload_destination: '%kernel.project_dir%/%app.public_dir%/img/skill'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
